### ISSUE TITLE
[1주차-주말공부] 주말에 공부할 내용을 정리합니다.

### ISSUE THREAD

**Issue by purin48** [woorifisa-projects/woochacha#1]
### 1주차 : 2023.07.31 ~ 2023.08.06

각자 맡은 분야 공부 분량을 정해서 코멘트로 남겨주세요!

다들 화이팅! 🔥🔥🔥

**Comment by purin48** [comment]
## 주말 공부 계획

- [ ] React 강의 12강 ~ 23강까지 듣기 !
- [ ] front 필요한 기술스택 정리

**Comment by seungg-0** [comment]
[ ] 실전! 스프링 부트와 JPA 활용1 다 듣기
[ ] 실전! 스프링 데이터 JPA 다 듣기
[ ] 구현 기능 추가 정리

**Comment by ShinChanCoding** [comment]
- [ ] 실전! 스프링 부트와 JPA 활용1 다 듣기
- [ ] 실전! 스프링 데이터 JPA 다 듣기
- [ ] React강의 시간 남으면 남는대로 다 듣기
